GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MDRiMzk0YzdiNDBjNDEzMTgxZmU2YzUiLCJpYXQiOjE2MTYwNTEzMzUsImV4cCI6MTYxNjA1NDkzNX0.zJw6kgNW1R5tB-EWa7dKFzyZ0vz56y-dKbWxNBDtdWg

{
    "title": "New day new life blog",
    "author": "Matti Luukkainen",
    "url": "https://imfeelinggood.io",
    "likes": "1"
}

###

DELETE http://localhost:3003/api/blogs/6052fcd7258bdd45443a0506
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MDRiMzk0YzdiNDBjNDEzMTgxZmU2YzUiLCJpYXQiOjE2MTYwNTEzMzUsImV4cCI6MTYxNjA1NDkzNX0.zJw6kgNW1R5tB-EWa7dKFzyZ0vz56y-dKbWxNBDtdWg

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "matti123",
    "name": "Matti Luukkainen"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "matti123"
}

###